### ISSUE TITLE
Discord for support and feature requests?

### ISSUE THREAD

**Issue by riahc3** [jloh02/valorant-client#1]
Hello

Would you consider making a Discord for support and feature requests?

**Comment by jloh02** [comment]
Sure! Currently, I'm doing a project rewrite on the [vite-dev](https://github.com/jloh02/valorant-chat-client/tree/vite-dev) branch to neaten up the code. Currently experimenting with Vite and Vue composition API. Will update here once I get to creating a Discord for supports and features. Meanwhile, the main medium for requests and support would be GitHub

**Comment by jloh02** [comment]
Created a simple Discord server for now

40dd8fc
